version: '3.8'

services:
  web:
    image: davud404/mi-app:latest
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: FLASK_TEST
      DB_USER: root
      DB_PASSWORD: root
      

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: FLASK_TEST
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mariadb

volumes:
  db_data:
